export enum SCREENS {
  HOME = 'HOME',
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  PROFILE = 'PROFILE',
  BOTTOM_TAB = 'BOTTOM_TAB',
  CART = 'CART',
  SETTING = 'SETTING',
  SHARE = 'SHARE',
  INFO = 'INFO',
  PAY = 'PAY',
  DETATIL_ACCOUNT = 'DETATIL_ACCOUNT',
  CHANGE_PASS = 'CHANGE_PASS',
  LINK_CARD = 'LINK_CARD',
  ADD_CARD = 'ADD_CARD',
  SEARCH_PRODUCT = 'SEARCH_PRODUCT',
  HISTORY_WITHDRAW = 'HISTORY_WITHDRAW',

}